// GENERATED by scripts/generate-geometry.mjs — do not edit by hand.
// Bounding box of every path of a tooth, in upper-right-quadrant
// coordinates. Lets the chart crop its viewBox and place tooth labels
// without a rendered-DOM measurement pass (there is none in React Native).

import {IToothBounds} from '../odontogram.types';

export const TOOTH_BOUNDS: readonly IToothBounds[] = [
  {name: '1', bounds: [154.075, 0.9, 207.544, 60.973]},
  {name: '2', bounds: [108.559, 5.584, 155.455, 63.14]},
  {name: '3', bounds: [71.033, 30.507, 129.452, 87.814]},
  {name: '4', bounds: [45.873, 63.003, 111.623, 112.145]},
  {name: '5', bounds: [28.91, 100.398, 92.653, 141.645]},
  {name: '6', bounds: [2.751, 137.201, 80.479, 203.519]},
  {name: '7', bounds: [-9.739, 198.282, 70.099, 263.092]},
  {name: '8', bounds: [0.533, 262.742, 64.075, 317.538]},
];
